language: node_js
node_js:
- '0.10'
before_script:
- cd kaizen
- gem update --system
- gem install compass
- npm install -g bower grunt-cli
- npm install grunt --save-dev connect-livereload
- bower install
deploy:
  provider: heroku
  api_key:
    secure: rRUae5KNrEH9Tia2I4RcIbCcE8laOESDdSrScIv7cQCd0jNBkg4P6VRy/lYFZAXSBqm9QLklYr/P+JH+l3+AB0Z77mX4LzUn9E2Hq//LpHyF7BHlwCPHSvQymacdWG0LA1uH9InRekuGrkCPiBFicwNqSdobmuG0motRkb/Wtm4=
  app: kaizen-dev
  on:
    repo: douglasnomizo/kaizen-box